services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: djangokubes:v1
    environment:
      - PORT=8000
      - POSTGRES_DB=dockerkubes
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=kosamtech
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=kosamtech
      - POSTGRES_DB=dockerkubes
    expose: ["5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose: ["6379"]
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388

volumes:
  postgres_data: {}
  redis_data: {}
  staticfiles:
    external: true
